# Generated by Django 2.2.7 on 2019-11-26 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('result', models.TextField(blank=True, null=True)),
                ('image' , models.ImageField(upload_to = 'pic_folder/', default = 'pic_folder/None/no-img.jpg')),
                ('image_result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
