# Generated by Django 2.2.7 on 2019-11-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191128_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pln',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
