# Generated by Django 2.2.7 on 2019-12-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191128_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pln',
            name='emotion',
            field=models.CharField(choices=[('alegria', 'Alegría'), ('confianza', 'Confianza'), ('miedo', 'Miedo'), ('sorpresa', 'Sorpresa'), ('tristeza', 'Tristeza'), ('asco', 'Asco'), ('anticipacion', 'Anticipación'), ('enojo', 'Enojo')], default='alegria', max_length=9),
        ),
    ]
