# Generated by Django 2.2.7 on 2019-12-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191202_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pln',
            name='image_result',
        ),
        migrations.RemoveField(
            model_name='pln',
            name='test',
        ),
        migrations.AddField(
            model_name='pln',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
