# Generated by Django 2.2.7 on 2019-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_pln_image_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='pln',
            name='res_eval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pln',
            name='emotion',
            field=models.CharField(choices=[('joy', 'Alegría'), ('trust', 'Confianza'), ('fear', 'Miedo'), ('surprise', 'Sorpresa'), ('sadness', 'Tristeza'), ('disgust', 'Asco'), ('anticipation', 'Anticipación'), ('anger', 'Enojo')], default='joy', max_length=9),
        ),
    ]
