# Generated by Django 2.2.7 on 2019-12-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191203_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='pln',
            name='list_res',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
