# Generated by Django 2.2.7 on 2019-12-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_pln_list_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='pln',
            name='list_emotion',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
