# Generated by Django 2.2.7 on 2019-12-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_pln_list_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pln',
            name='emotion',
            field=models.CharField(choices=[('joy', 'Alegría'), ('trust', 'Confianza'), ('fear', 'Miedo'), ('surprise', 'Sorpresa'), ('sadness', 'Tristeza'), ('disgust', 'Asco'), ('anticipation', 'Anticipación'), ('anger', 'Enojo')], default='joy', max_length=15),
        ),
        migrations.AlterField(
            model_name='pln',
            name='list_emotion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pln',
            name='list_res',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
