# Generated by Django 2.2.7 on 2020-02-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191204_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pln',
            name='emotion',
            field=models.CharField(choices=[('joy', 'Alegría'), ('trust', 'Confianza'), ('fear', 'Miedo'), ('surprise', 'Sorpresa'), ('sadness', 'Tristeza'), ('disgust', 'Asco'), ('anticipation', 'Anticipación'), ('anger', 'Enojo')], default='joy', help_text='La emoción que debe seleccionar es, la que el autor cree que esta transmitiendo con el texto ingresado anteriormente', max_length=15),
        ),
        migrations.AlterField(
            model_name='pln',
            name='text',
            field=models.TextField(max_length=700),
        ),
    ]
