# Generated by Django 2.2.7 on 2020-02-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200216_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='pln',
            name='anger',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='pln',
            name='anticip',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='pln',
            name='disgust',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='pln',
            name='fear',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='pln',
            name='joy',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='pln',
            name='sadness',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='pln',
            name='surprise',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='pln',
            name='trust',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
