# Generated by Django 2.2.7 on 2020-02-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200217_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pln',
            name='list_emotion',
        ),
        migrations.RemoveField(
            model_name='pln',
            name='list_res',
        ),
    ]
