# Generated by Django 2.2.7 on 2020-02-19 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200217_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pln',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
