# Generated by Django 2.2.7 on 2020-02-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200218_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pln',
            name='text',
            field=models.TextField(max_length=700),
        ),
    ]
