# Generated by Django 2.2.7 on 2020-02-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200218_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pln',
            name='text',
            field=models.CharField(max_length=700),
        ),
    ]
