# Generated by Django 2.2.7 on 2020-02-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200218_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pln',
            name='text',
        ),
    ]
